/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElIcon: (typeof import('element-plus/es'))['ElIcon'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElMenu: (typeof import('element-plus/es'))['ElMenu'];
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch'];
    ElTable: (typeof import('element-plus/es'))['ElTable'];
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
    FooterView: (typeof import('./src/components/layout/pc/footerView.vue'))['default'];
    HeaderView: (typeof import('./src/components/layout/pc/headerView.vue'))['default'];
    LeftView: (typeof import('./src/components/layout/pc/leftView.vue'))['default'];
    LottoryPicker: (typeof import('./src/components/toy/lottoryPicker.vue'))['default'];
    LottorySpinner: (typeof import('./src/components/toy/lottorySpinner.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterMiddle: (typeof import('./src/components/layout/pc/routerMiddle.vue'))['default'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
